name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo under GH workspace
      uses: actions/checkout@v3

    - name: Use nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install deps without updating package-lock.json
      run: npm i --no-save

    - name: Install Playwright for Storybook
      run: npx playwright install --with-deps

    - name: Run the CI build
      run: npm run ci

    - name: Serve Storybook and run tests
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server docs --port 6006 --silent" \
          "npx wait-on tcp:6006 && npm run test-storybook"

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
