name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo under GH workspace
      uses: actions/checkout@v3

    - name: Build docker image
      run: docker compose build

    - name: Run the CI build
      run: docker compose run --rm web npm run ci

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
